config/routes.rb
Rails.application.routes.draw do
  resources :orders, only: [:index, :create, :show, :edit,:update, :destroy]
  resources :restaurants, only: [:index, :show]


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :order_items
    has_many :orders, through: :order_items
    belongs_to :restaurant
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items
    has_many :items, through: :order_items
    belongs_to :restaurant

    def price
        self.items.map {|item| item.price }.sum
    end 

    # def item_collection
    #     self.items.each {|item| item.name}
        
    # end 

   
end 

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :item
    belongs_to :order
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many :orders
    has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  def index
    @orders = Order.all
  end
  def edit
    @order = Order.find(params[:id])
  end
  def update
   @order =  Order.find(params[:id])
   @order.update(restaurant_id: params[:restaurant][:id], date: @date)
   orderitemsarray =  @order.order_items

   orderitemsarray[0].update(order_id: @order.id, item_id: params[:items][:item_1])
   orderitemsarray[1].update(order_id: @order.id, item_id: params[:items][:item_2])
   orderitemsarray[2].update(order_id: @order.id, item_id: params[:items][:item_3])
   
  

   redirect_to order_path(@order.id)
  
  end

  def destroy
    #byebug
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to orders_path
  end
  def create
    @date = Time.new.strftime "%D"
    @order = Order.create(restaurant_id: params[:restaurant][:id], date: @date)
    OrderItem.create(order_id: @order.id, item_id: params[:items][:item_1])
    OrderItem.create(order_id: @order.id, item_id: params[:items][:item_2])
    OrderItem.create(order_id: @order.id, item_id: params[:items][:item_3])
    redirect_to  @order
  end

  

  
  def show
  @order = Order.find(params[:id])
    
  end

  


end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurant = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<link rel="stylesheet" href="https://unpkg.com/bulmaswatch/minty/bulmaswatch.min.css">

<html>
  <head>
    <title>Delivery1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/edit.html.erb
<h1> Edit your order before it's too late! </h1>

<h2> Edit your  order here </h2>
<%= form_with model: @order do |f| %>
<%= hidden_field :restaurant, :id, value: @order.restaurant.id %>
<%= collection_select :items, :item_1,  Item.all, :id, :name%>
<%= collection_select :items, :item_2,  Item.all, :id, :name%>
<%= collection_select :items, :item_3,  Item.all, :id, :name%>

<%= f.submit "Update" %>

<% end %>



<%= link_to 'Back', restaurants_path %>

app/views/orders/index.html.erb
<h1> All the orders you have made </h1>

<p>
  <strong>Here's your most recent order! Click to view/edit it!</strong>
  <p> <%= link_to "View your last order", order_path(@orders.last.id) %>
  <p> <%= link_to  "Edit your last order", edit_order_path(@orders.last.id) %>
      
  <p> You've made orders from the following restaurants: </p> 
   <ul>
   <% @orders.each do |order| %>
   <li> <%= link_to order.restaurant.name, order_path(order) %> 
    date: <%=  order.date%> 
    <%= button_to 'delete order', order_path(order.id),
              method: :delete,
              data: { confirm: 'Are you sure you want to delete your order?' } %>
    
    </li >
   <% end %>
    </ul>
  
</p>    
  

app/views/orders/new.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/show.html.erb
<h1> My order </h1>


<p>
  <strong></strong>
  <p> These are your items: </p> 
   <ul>
   <% for item in @order.items %>
   <li> <%= item.name %> <img style="width: 20%;" src="<%= item.image %>" /> 
   </li >
   
   <% end %>
    </ul>
  
</p>
 


<h2>Your total is: £ <%=  @order.price %> </h2>
<h2> Your order is being prepared!<h2>

<h4> <%= link_to 'Edit', edit_order_path %> </h4>
<h4> <%= link_to 'All orders', orders_path %> </h4>

<h3> <%= link_to 'Click here if you would like to make a new order ', restaurants_path %> </h3>

app/views/restaurants/index.html.erb
<h1></h1>

<h1>All of your awesome restaurant choices!</h1>

  <h3> Click the restaurant of your choice to make the order </h3>
  
  <% @restaurant.map do |rest| %>
    <li>
  <%= link_to rest.name, restaurant_path(rest) %> 
  <%= rest.address%>
    </li>
      <% end %>
  

app/views/restaurants/show.html.erb
<h3>You've chosen:</h3>

<h1> <%= @restaurant.name %> </h2>

<h2> Create your  order here </h2>
<%= form_with url: '/orders' do |f|%>
<%= hidden_field :restaurant, :id, value: @restaurant.id %>
<%= collection_select :items, :item_1,  Item.all, :id, :name%>
<%= collection_select :items, :item_2,  Item.all, :id, :name%>
<%= collection_select :items, :item_3,  Item.all, :id, :name%>

<%= f.submit "create"%>

<% end %>